import java.util.*;

public class Main
{
   public static void main(String [] args)
   {
      Scanner it=new Scanner(System.in);
   
   //Q1 how do you use the scanner to populate the following variables
  /* System.out.println("Please enter your First Name:  ");
   String x= it.nextLine();
   System.out.println("Hi "+x+"!"); 
   System.out.println("Please enter your Age: ");
  int age = it.nextInt();
  System.out.println("Please enter your Height in cm: ");
  double height=it.nextDouble();
  System.out.println("You are "+age+" years old and are "+height+" cm tall!"); */
  
  int num=723;
   //Q2
   //how do you print the hundreds column
   System.out.println("hundreds digit="+num/100);
   //how do you print the tens column of the original number
   System.out.println("tens digit="+(num/10)%10);
   //how do you print the 1's column
   System.out.println("ones digit="+num%10);
 

   //System.out.println("tens column="+num%10);
         
   
   //Q3 What is the output when val is printed
   
      int val=-123;
      val--; //-124
      val--; //-125
      val--; //-126- final output :)
   System.out.println(val);
   
   //Q4
   //correct the code
    int sum = (int)-123.456;
   
   //Q5 How do you store the phrase Have a nice day in a String variable called greeting
   String greeting = "Have a nice day ";
   System.out.println(greeting);
   //Q6
  // What is the output of the following lines of code?
   System.out.println(100+100); //200
   System.out.println("s"+100+100);// s100100
   System.out.println(100+(100+100));//300
      
   //Q7 - find the true average of 3 plus 4
   double average = (double)(3+4)/2;
   System.out.println(average);
   //Q8
      int num2=5;
      num2+=10;
      num2*=3;
      num2-=5;
      //System.out.println("num2%3="+num2%3);
      
   //Q9 what is generated by the following lines of code
     // double x=Math.random(); 0.0<=x<1.0
   
   //Q10 
      int total_mins=500;
      int hours= total_mins/60;
      int mins= total_mins%60;
      System.out.println("500 minutes is equivalent to " +hours+ " hours and " + mins +" minutes.");
      
   //Q11 
      int totalPennies=1234;
   //if I turned these pennies into the bank, what is the maximum number of quarters I would receive?
   //how much change is left over in pennies?
    int maxNumQuarters= totalPennies/25;
  int numLeftOverPennies= totalPennies%25;
  System.out.println("If you turned in "+totalPennies+" into the bank, you would recieve a max of "+maxNumQuarters+" quarters and there would be "+numLeftOverPennies+" pennies left over.");  
    
    
   
   
   
   
   }
}